name: Daily Gatsby Build

on:
  schedule:
    # Run every day at 10:00am UTC
    - cron: "0 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gatsby Webhook
        run: |
          curl -X POST ${{secrets.gatsby_webhook}} --header "x-gatsby-cache: false"
